# Generated by Django 5.0 on 2023-12-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="satatus",
            field=models.CharField(max_length=50),
        ),
    ]
